# 17장 딥러닝을 이용한 자연어 처리

[<img src="https://raw.githubusercontent.com/taehojo/taehojo.github.io/master/assets/images/linktocolab.png" align="left"/> ](https://colab.research.google.com/github/taehojo/deeplearning/blob/master/colab/ch17-colab.ipynb)

## 1. 텍스트의 토큰화

In [6]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential, load_model
from numpy import array

# 케라스의 텍스트 전처리와 관련한 함수중 text_to_word_sequence 함수를 불러옵니다.
#from tensorflow.keras.preprocessing.text import text_to_word_sequence
 

## 2. 모델 불러오기

In [7]:
# 모델 체크(최적 학습), 종료
modelpath="./data/model/ch17_review_md.hdf5"

model = load_model(modelpath)

In [8]:
# 토큰 불러오기
import pickle

# 토큰 패스
tokenpath="./data/model/ch17_review_token.pickle"

with open(tokenpath, 'rb') as handle:
    token = pickle.load(handle)
    
    print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [9]:
# 예측률 검증
#  "참 너무 별로예요" 는 부정이지만, 분석 데이터 기준으로는 긍정 평가임
test_doc = ["글쎄요 너무 최고예요", "참 너무 별로예요", "글쎄요 지루하네요","재미없어요","이상한 문구는 어떻게 되나요"];
classes_y = array([1,0,0,0,0])

test = token.texts_to_sequences(test_doc)
print(test)
padded_test = pad_sequences(test, 4)  
print(padded_test)

#model.predict(padded_test)

print("\n Accuracy: %.4f" % (model.evaluate(padded_test, classes_y)[1]))

[[14, 1, 3], [4, 1, 15], [14, 17], [20], []]
[[ 0 14  1  3]
 [ 0  4  1 15]
 [ 0  0 14 17]
 [ 0  0  0 20]
 [ 0  0  0  0]]
1/1 [==============================] - 0s 91ms/step - loss: 0.6832 - accuracy: 0.8000

 Accuracy: 0.8000
